import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import test from 'node:test';

import { generateManifests } from '../tools/knowledge-context.mts';

function fixture(files: Record<string, string>): string {
  const root = mkdtempSync(join(tmpdir(), 'knowledge-context-test-'));

  for (const [path, content] of Object.entries(files)) {
    const fullPath = join(root, path);
    mkdirSync(dirname(fullPath), { recursive: true });
    writeFileSync(fullPath, content);
  }

  return root;
}

const CATALOG = `domains:
  test:
    path: knowledge/test
    description: Test domain rules.
    decision_index: knowledge/test/decisions/index.yaml
    code_paths: [src/test/]
`;

function doc(id: string, status: string, extra: Record<string, string> = {}): string {
  const fields: Record<string, string> = {
    id,
    title: `Title of ${id}`,
    status,
    created: '2026-09-01',
    updated: '2026-09-02',
    authors: '[test]',
    scope: '[test]',
    tags: `[${id.includes('DR-') ? 'decision' : id.includes('RFC-') ? 'rfc' : 'spec'}]`,
    depends_on: '[]',
    related: '[]',
    ...extra,
  };
  const lines = Object.entries(fields).map(([key, value]) => `${key}: ${value}`);
  return `---\n${lines.join('\n')}\n---\n\n# ${id}\n`;
}

test('renders the domain manifest with anchors, decisions, and pending drafts', () => {
  const root = fixture({
    'knowledge/index.yaml': CATALOG + '    current:\n      specification: SPEC-001\n',
    'knowledge/test/decisions/index.yaml': 'current:\n  topic.one: DR-001\n',
    'knowledge/test/decisions/DR-001.md': doc('DR-001', 'accepted'),
    'knowledge/test/specs/SPEC-001.md': doc('SPEC-001', 'current', { depends_on: '[DR-001]' }),
    'knowledge/test/rfcs/RFC-001.md': doc('RFC-001', 'draft', { drafted_by: 'agent', motivated_by: 'a conflict' }),
  });

  try {
    const manifests = generateManifests(root);
    assert.equal(manifests.length, 1);
    assert.equal(manifests[0].domain, 'test');
    assert.ok(manifests[0].file.endsWith(join('knowledge', 'test', 'CONTEXT.md')));

    const content = manifests[0].content;
    assert.match(content, /# Context: test/);
    assert.match(content, /Test domain rules\./);
    assert.match(content, /\*\*Governs code:\*\* `src\/test\/`/);
    assert.match(content, /\| specification \| SPEC-001 \| Title of SPEC-001 \| 2026-09-02 \|/);
    assert.match(content, /\| topic\.one \| DR-001 \| Title of DR-001 \| 2026-09-02 \|/);
    assert.match(content, /## Pending — NOT current truth, do not obey/);
    assert.match(content, /`RFC-001` \(draft, agent-drafted\): Title of RFC-001/);
    assert.match(content, /GENERATED by "npm run knowledge:context -- --write"/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('manifest output is deterministic and omits pending section when empty', () => {
  const root = fixture({
    'knowledge/index.yaml': CATALOG,
    'knowledge/test/decisions/index.yaml': 'current: {}\n',
    'knowledge/test/README.md': '# Test\n',
  });

  try {
    const [first] = generateManifests(root);
    const [second] = generateManifests(root);
    assert.equal(first.content, second.content);
    assert.match(first.content, /## Current truth\n\nNone yet\./);
    assert.match(first.content, /## Active decisions\n\nNone yet\./);
    assert.doesNotMatch(first.content, /## Pending/);
    assert.doesNotMatch(first.content, /Generated: \d/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
