// Retrieval bundles for Knowledge-Driven Engineering (DR-008, DR-009).
//
//   knowledge:context -- <file-or-domain>   print the context receipt (Gate 5)
//   knowledge:context -- --write [names]    render CONTEXT.md manifests
//   knowledge:context -- --check            fail if committed manifests drifted
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import {
  checkKnowledge,
  loadCatalogs,
  parseDecisionIndex,
  values,
  type Catalog,
  type CatalogDomain,
} from './knowledge-check.mts';

type DocumentRecord = ReturnType<typeof checkKnowledge>['documents'][number];

export type Manifest = { domain: string; file: string; content: string };

function pendingDocuments(root: string, domain: CatalogDomain, documents: DocumentRecord[]): DocumentRecord[] {
  if (!domain.path) return [];
  const domainDir = domain.path.replace(/\/$/, '') + '/';

  return documents
    .filter((document) => {
      const rel = relative(root, document.file);
      if (!rel.startsWith(domainDir)) return false;
      const status = String(document.data.status);
      return status === 'draft' || status === 'in-review';
    })
    .sort((a, b) => a.file.localeCompare(b.file));
}

function renderManifest(
  root: string,
  name: string,
  domain: CatalogDomain,
  byId: Map<string, DocumentRecord>,
  documents: DocumentRecord[],
): string {
  const lines: string[] = [
    '<!-- GENERATED by "npm run knowledge:context -- --write". Do not edit by hand:',
    '     CI fails when this file differs from the generator output. -->',
    '',
    `# Context: ${name}`,
    '',
    domain.description ?? 'No domain description in the catalog yet.',
  ];

  if (domain.codePaths.length > 0) {
    lines.push('', `**Governs code:** ${domain.codePaths.map((path) => `\`${path}\``).join(' · ')}`);
  }

  const row = (label: string, id: string): string => {
    const document = byId.get(id);
    const title = document ? String(document.data.title) : '(missing document)';
    const updated = document ? values(document.data, 'updated')[0] ?? '' : '';
    return `| ${label} | ${id} | ${title} | ${updated} |`;
  };

  lines.push('', '## Current truth', '');
  const anchors = Object.entries(domain.current);
  if (anchors.length === 0) {
    lines.push('None yet.');
  } else {
    lines.push('| Role | ID | Title | Updated |', '| --- | --- | --- | --- |');
    for (const [role, id] of anchors) lines.push(row(role, id));
  }

  lines.push('', '## Active decisions', '');
  const decisions = domain.decisionIndex ? parseDecisionIndex(resolve(root, domain.decisionIndex)) ?? {} : {};
  const topics = Object.entries(decisions);
  if (topics.length === 0) {
    lines.push('None yet.');
  } else {
    lines.push('| Topic | ID | Title | Updated |', '| --- | --- | --- | --- |');
    for (const [topic, id] of topics) lines.push(row(topic, id));
  }

  const pending = pendingDocuments(root, domain, documents);
  if (pending.length > 0) {
    lines.push('', '## Pending — NOT current truth, do not obey', '');
    for (const document of pending) {
      const status = String(document.data.status);
      const draftedBy = String(document.data.drafted_by ?? 'human');
      lines.push(`- \`${String(document.data.id)}\` (${status}, ${draftedBy}-drafted): ${String(document.data.title)}`);
    }
  }

  lines.push(
    '',
    '## Rules',
    '',
    '- This file is the map, not the rationale. Open the documents above before changing behavior.',
    '- Report conflicts between code and canonical knowledge; do not resolve them silently.',
    '- Precedence: active decision > current spec > other domain docs > implementation > history.',
    '',
  );

  return lines.join('\n');
}

export function generateManifests(root = process.cwd()): Manifest[] {
  const catalogs = loadCatalogs(root);
  const { documents } = checkKnowledge(root);
  const byId = new Map(documents.map((document) => [String(document.data.id), document]));
  const manifests: Manifest[] = [];

  for (const catalog of catalogs) {
    for (const [name, domain] of catalog.domains) {
      if (!domain.path) continue;
      manifests.push({
        domain: name,
        file: join(root, domain.path, 'CONTEXT.md'),
        content: renderManifest(root, name, domain, byId, documents),
      });
    }
  }

  return manifests;
}

const executedDirectly = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;

if (executedDirectly) {
  const root = process.cwd();
  const args = process.argv.slice(2);

  if (args[0] === '--write') {
    const names = args.slice(1);
    const manifests = generateManifests(root).filter((manifest) => names.length === 0 || names.includes(manifest.domain));

    if (manifests.length === 0) {
      console.error(names.length > 0 ? `no cataloged domain matches: ${names.join(', ')}` : 'no cataloged domains found');
      process.exit(1);
    }

    for (const manifest of manifests) {
      writeFileSync(manifest.file, manifest.content);
      console.log(`wrote ${relative(root, manifest.file)}`);
    }
  } else if (args[0] === '--check') {
    let checked = 0;
    let absent = 0;
    const stale: string[] = [];

    for (const manifest of generateManifests(root)) {
      if (!existsSync(manifest.file)) {
        absent += 1;
        continue;
      }

      checked += 1;
      if (readFileSync(manifest.file, 'utf8') !== manifest.content) {
        stale.push(relative(root, manifest.file));
      }
    }

    if (stale.length > 0) {
      for (const file of stale) {
        console.error(`${file} is stale: regenerate with "npm run knowledge:context -- --write"`);
      }
      process.exit(1);
    }

    console.log(`manifests: ok (${checked} checked${absent > 0 ? `, ${absent} domain${absent === 1 ? '' : 's'} without manifest` : ''})`);
  } else {
    const input = args[0];

    if (!input) {
      console.error('usage: npm run knowledge:context -- <file-or-domain> | --write [domains] | --check');
      process.exit(1);
    }

    const catalogs = loadCatalogs(root);
    const { documents } = checkKnowledge(root);
    const byId = new Map(documents.map((document) => [String(document.data.id), document]));

    const describe = (id: string): string => {
      const document = byId.get(id);
      return document ? `${id} (${relative(root, document.file)})` : `${id} (unresolved)`;
    };

    type Match = { catalog: Catalog; name: string };
    const matches: Match[] = [];
    const asPath = relative(root, resolve(root, input));

    for (const catalog of catalogs) {
      for (const [name, domain] of catalog.domains) {
        const isDomainName = name === input;
        const ownsCode = domain.codePaths.some(
          (prefix) => asPath.startsWith(prefix.replace(/\/$/, '') + '/') || asPath === prefix.replace(/\/$/, ''),
        );
        const ownsKnowledge =
          domain.path !== undefined && (asPath.startsWith(domain.path.replace(/\/$/, '') + '/') || asPath === domain.path);

        if (isDomainName || ownsCode || ownsKnowledge) matches.push({ catalog, name });
      }
    }

    if (matches.length === 0) {
      const known = catalogs.flatMap((catalog) => [...catalog.domains.keys()]);
      console.error(`no domain matches ${input}. Known domains: ${known.join(', ')}. Map code with code_paths in the domain catalog.`);
      process.exit(1);
    }

    console.log('# Context Receipt');
    console.log('');
    console.log(`Input: ${input}`);
    console.log(`Generated: ${new Date().toISOString().slice(0, 10)}`);

    for (const { catalog, name } of matches) {
      const domain = catalog.domains.get(name)!;
      console.log('');
      console.log(`## Domain: ${name}`);
      console.log('');
      if (domain.path) console.log(`- Domain README: ${domain.path.replace(/\/$/, '')}/README.md`);

      for (const [role, id] of Object.entries(domain.current)) {
        console.log(`- ${role}: ${describe(id)}`);
      }

      if (domain.decisionIndex) {
        const decisions = parseDecisionIndex(resolve(root, domain.decisionIndex));
        for (const [topic, id] of Object.entries(decisions ?? {})) {
          console.log(`- active decision ${topic}: ${describe(id)}`);
        }
      }

      for (const document of pendingDocuments(root, domain, documents)) {
        const status = String(document.data.status);
        const draftedBy = String(document.data.drafted_by ?? 'human');
        console.log(
          `- pending ${status} (${draftedBy}-drafted, NOT current truth): ${String(document.data.id)} (${relative(root, document.file)})`,
        );
      }
    }

    console.log('');
    console.log('## Confirmation');
    console.log('');
    console.log('- Documents above were read before changing behavior.');
    console.log('- Conflicts found: <none | describe the conflict>');
  }
}
